### ISSUE TITLE
Missing google.api.ConfigChange

### ISSUE THREAD

**Issue by udoprog** [googleapis/googleapis#119]
I just attempted to build the protocol definitions for Java, and the only snag I encountered is a missing reference to `google.api.ConfigChange`.

You can find my complete build script here:
https://github.com/udoprog/googleapis/commit/5908cb5c2e0b96d69b16c91fa173f692d3737079

This includes [a patch](https://github.com/udoprog/googleapis/blob/5908cb5c2e0b96d69b16c91fa173f692d3737079/maven/patches/remove_config_change.diff) that comments out `google.api.ConfigChange` in order for everything to build.

Without this patch, I get a slew of this and a protoc build failure:
```
google/api/servicemanagement/v1/resources.proto:177:12: "google.api.ConfigChange" is not defined.
```

P.S. I don't expect this to be the official way to eventually build these bindings, but I'm using this so that I can't start working on things that interact with your services over gRPC, and official packages for the stubs appear to be missing.

**Comment by garrettjonesgoogle** [comment]
We have now added the missing proto in this commit: https://github.com/googleapis/googleapis/commit/a5cfecd86f020449d90974a9a92ba41ae173b0a5

proto file: https://github.com/googleapis/googleapis/blob/master/google/api/config_change.proto

**Comment by udoprog** [comment]
That looks like it will do it. Thank you!
