### ISSUE TITLE
Feedback on pubsub/v1 publisher.delete_topic in python

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/googleapis#13]
> What does "Generates NOT_FOUND if the topic does not exist." mean? This method doesn't have a documented return value. Is NOT_FOUND going to be a GaxError exception or is this just missing "Returns:" documentation

This comment is confusing in language-specific generated docs: #12 . 

> As rendered in "not deleted, but their topic field is set to _deleted-topic_." it seems like the latter _deleted-topic_ should be a quoted string.

**Comment by tbetbetbe** [comment]
In python, the gax layer does not return a value when the response is the empty proto.  The text in the comment is confusing because of use of the verb 'generates' which can have a particular meaning in python, and also because in fact the value NOT_FOUND will be a status_code field in a thrown exception, and using the verb 'generates' is not how you'd describe that.

Something more generic like 'fails with status code NOT_FOUND' would be clearer, and would probably work in many languages

**Comment by tbetbetbe** [comment]
This also affects the docs for the [publisher.publish](http://pythonhosted.org/gax-google-pubsub-v1/google.pubsub.v1.publisher_api.html#google.pubsub.v1.publisher_api.PublisherApi.publish) method

**Comment by geigerj** [comment]
@saicheems Is this something that can be addressed via your proposals on idiomatic proto documentation?

**Comment by saicheems** [comment]
It's part of the scope of those proposals, but I've still not come up with the right idea yet. My plan is to tackle it next, after closing required/optional and leading sentences in docstrings.
