### ISSUE TITLE
prediction_service.proto missing necessary HttpBody

### ISSUE THREAD

**Issue by jrheizelman** [googleapis/googleapis#143]
In /google/cloud/ml/v1beta1/prediction_service.proto the message PredictRequest relies on a type google.api.HttpBody that is not defined, and the necessary proto is missing from the google/api folder

**Comment by geigerj** [comment]
Thanks for the report! This is fixed in https://github.com/googleapis/googleapis/commit/38bf1620f2fc3b892e83885506e65d28f204cf0c#diff-8c28a0bbad8bfda264dc68f06ed88b07R20
