### ISSUE TITLE
Meta: make it clear that the call may fail with the INVALID_ARGUMENT status code

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/googleapis#15]
* calls that may fail due to bad input values should indicate that they may fail with the INVALID_ARGUMENT code
* any methods with constraints that may cause (i.e, nearly all), should contain text that explains that the call might fail with this error code

**Comment by bjwatson** [comment]
Wrap the gRPC INVALID_ARGUMENT error with a pythonic VALUE_ERROR.

**Comment by bjwatson** [comment]
This has been moved to `gax-python`
