### ISSUE TITLE
Sort out go_package option

### ISSUE THREAD

**Issue by pongad** [googleapis/googleapis#161]
Currently Go needs `go_package` option to properly generate imports for types under `google/api`.

We have to update Google-internal versions of these proto files first. Setting up this issue to track pushing the change to GitHub.

The following are the PRs to work around the issue:
- https://github.com/googleapis/toolkit/pull/536

**Comment by vchudnov-g** [comment]
Could you also include here the PRs/files where we're using a manual workaround for now?

**Comment by pongad** [comment]
@vchudnov-g Added to the issue description.

**Comment by wora** [comment]
I think this has been address by now.

**Comment by pongad** [comment]
@wora Agreed. Closing this.
