### ISSUE TITLE
longrunning_gapic.yaml "file" issue?

### ISSUE THREAD

**Issue by jskeet** [googleapis/googleapis#182]
In https://github.com/googleapis/googleapis/blob/master/google/longrunning/longrunning_gapic.yaml we have:

```
license_header:
  copyright_file: copyright-google.txt
  file: license-header-bsd-3-clause.txt
```

I _suspect_ that's meant to be:

```
license_header:
  copyright_file: copyright-google.txt
  license_file: license-header-bsd-3-clause.txt
```

... that certainly builds, whereas the former doesn't.

This may be due to the timing of files being synced/built/etc though.

**Comment by garrettjonesgoogle** [comment]
yes indeed, that was a local timing issue.
