### ISSUE TITLE
Proper scopes are missing from monitoring.yaml

### ISSUE THREAD

**Issue by jmdobry** [googleapis/googleapis#188]
From the [public discovery doc](https://monitoring.googleapis.com/$discovery/rest?version=v3), the Monitoring v3 API appears to require:

```
https://www.googleapis.com/auth/cloud-platform
https://www.googleapis.com/auth/monitoring.read
https://www.googleapis.com/auth/monitoring.write
https://www.googleapis.com/auth/monitoring
```

Without these scopes, gRPC requests to the Monitoring v3 API made by generated Gapic code fail with code 16 (401 unauthorized).

**Comment by jmdobry** [comment]
After more investigation, the scopes _are_ in `monitoring.yaml`, but the scopes are not emitted in the generated Gapic code.

For example: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/monitoring/src/v3/metric_service_api.js#L60

**Comment by geigerj** [comment]
@jmuk Could you take a look?

**Comment by jmuk** [comment]
Seems forgotten to be closed.
