### ISSUE TITLE
Support for Cloud Resource Manager v1 API

### ISSUE THREAD

**Issue by adamtanner** [googleapis/googleapis#206]
Thanks! :grin:

**Comment by geigerj** [comment]
Is this a request for protos to be added to this repo? If so, we should track this internally rather than on this repository; I can direct you to some resources on how that works.

**Comment by adamtanner** [comment]
Yep, that would be great! I'm adamtanner@ internally as well.

**Comment by wora** [comment]
Due to design issues, we may release v2 API instead.

**Comment by bjwatson** [comment]
Closing, since this should be handled using the internal mechanism for open-sourcing protos.
