### ISSUE TITLE
Config for ErrorStatsServiceClient.ListGroupStats doesn't have filtering

### ISSUE THREAD

**Issue by jskeet** [googleapis/googleapis#210]
(Root cause of https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/603)

With my limited understanding of the config, I believe this needs a change here:
https://github.com/googleapis/googleapis/blob/master/google/devtools/clouderrorreporting/v1beta1/errorreporting_gapic.yaml#L132

Assigning to Jacob as first person to commit this config - feel free to reassign, of course...

**Comment by geigerj** [comment]
cc: @garrettjonesgoogle for more context on flattening (Python doesn't use it)

@jskeet I think the configuration should be OK. I see that this method is marked `request_object_method: true`. This is supposed to mean that you can pass optional fields like [`service_filter`](https://github.com/googleapis/googleapis/blob/master/google/devtools/clouderrorreporting/v1beta1/error_stats_service.proto#L62) by constructing `ListGroupStatsRequest` explicitly and passing that to the method. The general strategy we've been observing, AFAIK, is to make constructing the request message the _only_ way to pass optional fields, although technically we could add another flatting config to generate a method overload that takes `service_filter` as a parameter.

**Comment by jskeet** [comment]
Right. Currently the C# codegen doesn't generate a request-accepting method. We've been anticipating doing so at some point, but possibly in a "relatively hard to get at" way - it sounds like it probably shouldn't be so hard.

// cc @chrisdunelm for context.

**Comment by geigerj** [comment]
My intuition is that generating a request-accepting method in C# is probably a better way to solve this problem than modifying the config, for consistency with Java. But @garrettjonesgoogle's feedback here is going to be more meaningful than mine.

**Comment by garrettjonesgoogle** [comment]
Yeah, what @geigerj said. Some request objects can get pretty large - 5+ fields starts getting unwieldy, especially in Java. That's actually the whole point of the flattening config. If C# always wants all parameters flattened out, then you'd want to ignore the config altogether.

**Comment by geigerj** [comment]
I'm going to close this issue; feel free to re-open if we actually do want to modify the config here.
