### ISSUE TITLE
LANGUAGE variable in Makefile elided by LANGUAGE environment variable

### ISSUE THREAD

**Issue by allquixotic** [googleapis/googleapis#222]
The LANGUAGE variable in the Makefile is elided by the LANGUAGE environment variable. 

On many systems (including Ubuntu and MSYS2), the LANGUAGE environment variable is defined, e.g. as "en_US" or something like that.

This leads to `make` producing output like this:

```
$ make
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --en_US_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_en_US_plugin google/api/annotations.proto
protoc-gen-en_US: program not found or is not executable
--en_US_out: protoc-gen-en_US: Plugin failed with status code 1.
Makefile:41: recipe for target 'google/api/annotations.pb.cc' failed
make: *** [google/api/annotations.pb.cc] Error 1
```

Changing the variable name in the Makefile to something different - anything not already defined in the environment - fixes the issue.

**Comment by bloodcarter** [comment]
+1

**Comment by wora** [comment]
According to POSIX standard, http://pubs.opengroup.org/onlinepubs/
009695399/basedefs/xbd_chap08.html, LANG is the standard environment
variable.

This  Makefile is intended to verify the entire repo is buildable. It is
not intended to be used as "make" without a language.

**Comment by allquixotic** [comment]
From the README.md:

 > To generate gRPC source code for Google APIs in this repository, you first need to install both Protocol Buffers and gRPC on your local machine. Then you can run `make all` in this directory to generate the code.

Running `make all` is synonymous with running `make`, so the intention of the Makefile is not at all clear from the readme.

Nowhere does it say that the user is responsible for specifying a language, though in practice that's what ends up happening (or the user has to edit the Makefile, which is even less friendly).

Suggest updating the docs to provide the recommended way for users to generate the bindings for e.g. C++ and C#.

**Comment by geigerj** [comment]
If the makefile was originally just intended to ensure that the entire repo is buildable, as @wora said, we no longer need it; there are other processes currently used to check this, and no one currently maintains that file. We will remove the makefile. In the meantime, please invoke `protoc` directly.

I will update the docs and remove this file.

**Comment by wora** [comment]
I will update the doc.

**Comment by wora** [comment]
Please keep the Makefile and I will fix it. We need to demonstrate the repo
can be easily built with absolutely minimum dependency. If it is hard to
keep the Makefile live, then the repo setup is too complicated.

**Comment by geigerj** [comment]
wora@ Ok, but let's change the name of the `LANGUAGE` variable to avoid this confusion.

**Comment by wora** [comment]
I updated the main README.md to mention the LANGUAGE parameter must be passed explicitly. Since LANGUAGE is not a POSIX standard env, I don't think we have to avoid it.

**Comment by jmuk** [comment]
Thank you for clarifying the purpose of Makefile. Closing.
