### ISSUE TITLE
Fails to build from source on Ubuntu 16.04

### ISSUE THREAD

**Issue by allquixotic** [googleapis/googleapis#223]
On Ubuntu 16.04, I compiled grpc (git master) from source using the recommended method and installed it in /usr/local. I used the protobuf version taken from grpc itself.

`which protoc` returns `/usr/local/bin/protoc` which is from the `third_party` directory of grpc.

When I try to compile googleapis, it succeeds to generate a bunch of files and passes many `protoc` invocations but fails on this one:

```
protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin /usr/local/include/google/protobuf/compiler/plugin.proto
[libprotobuf ERROR google/protobuf/io/printer.cc:148]  Undefined variable: NAME", and will then be used when the
// flag "--
```

When I look for this weird string, I find it here, in the grpc sources:

```
$ ack 'and will then be used when the' ~/dev
/home/sean/dev/grpc/third_party/nanopb/generator/proto/plugin.proto
44:// plugin should be named "protoc-gen-$NAME", and will then be used when the

/home/sean/dev/grpc/third_party/protobuf/src/google/protobuf/compiler/plugin.proto
44:// plugin should be named "protoc-gen-$NAME", and will then be used when the
```

which installed to my system path as `/usr/local/include/google/protobuf/compiler/plugin.proto`

If I delete lines 44 and 45 (**comments**?!) from that file, the googleapis build proceeds smoothly.

What package is at fault here? This clearly seems to be a bug where it's thinking that a comment is actual code.

**Comment by geigerj** [comment]
This repository contains proto buffer definitions for Google APIs, but doesn't directly deal with the proto compiler itself. The folks over at https://github.com/google/protobuf may be able to provide more assistance with this issue -- I'd try filing over there.
