### ISSUE TITLE
Cannot build from source: no protobuf

### ISSUE THREAD

**Issue by bloodcarter** [googleapis/googleapis#224]
Compiled and installed gRPC as of here: https://github.com/grpc/grpc/blob/master/INSTALL.md.
When trying to compile:
```
find: ‘/usr/local/include/google/protobuf’: No such file or directory
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/logging/type/http_request.proto
google/logging/type/http_request.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
Makefile:41: recipe for target 'google/logging/type/http_request.pb.cc' failed
make: *** [google/logging/type/http_request.pb.cc] Error 1
```

**Comment by jmuk** [comment]
- you need to set `GRPCPLUGIN` and `PROTOINCLUDE` properly for your environment.
- `Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".` this error message indicates that your protobuf version is older. Use protobuf 3.

**Comment by bloodcarter** [comment]
OK, it compiled, but now I have this error:
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:67] This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/bloodcarter/googleapis/gens/google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/bloodcarter/googleapis/gens/google/protobuf/any.pb.cc".)
```

**Comment by jmuk** [comment]
That error message looks like you're in trouble of setting up protobuf. Does your protoc correctly compile grpc samples outside of this repository?

**Comment by jmuk** [comment]
BTW, can I ask you the purpose why you are trying to make?

`Makefile` was created long ago, but I don't know any active users -- in my understanding, this repository is for proto files and configurations, not recipes to build something. I'm wondering what this file is good for. If you find this `Makefile` useful, please let me know.

**Comment by wora** [comment]
The purpose of the Makefile is very simple: make sure the entire repo is
compliable for all proto languages. And it can be done without complicated
build system.

**Comment by bloodcarter** [comment]
Eventually I've managed to get it working by reinstalling everything from the scratch. Not sure what was the problem. Maybe, it's a good idea to review the repo once again and update it.
