### ISSUE TITLE
Remove Makefile?

### ISSUE THREAD

**Issue by jmuk** [googleapis/googleapis#225]
I've seen a few bug reports about the `Makefile`. I don't know how many people are using that actively (at least our team doesn't use it at all, right?)

Can we simply remove it?

**Comment by wora** [comment]
The purpose for the Makefile is to test and verify the entire repository
can be built for all proto supported languages. If it doesn't work, it
means some part of the repository is not set up according to original
design.

Note: Google client libraries is only one set of customers of the repo, but
we should not treat it especially.

**Comment by jmuk** [comment]
Okay, then let's keep it as-is.
