### ISSUE TITLE
What is the official Google package for google.api.HttpRule ?

### ISSUE THREAD

**Issue by TamalSaha** [googleapis/googleapis#229]
Hi,
We are using grpc-gateway which uses google.api.HttpRule. To generate Java code, we need access to Java version of this proto. Is there a official jar file for this?

Thanks.

**Comment by wora** [comment]
We provide the source code so you can compile it any way you like. I am not sure what Google package refers to. Do you mean maven binary package name or java source package name.

**Comment by TamalSaha** [comment]
@wora, I was wondering if there is any official jar file released to maven for this. It feels a little weird that everyone is building their own version of this file in their java protobuf library.

**Comment by garrettjonesgoogle** [comment]
Here it is: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.api.grpc%22%20AND%20a%3A%22grpc-google-common-protos%22

**Comment by garrettjonesgoogle** [comment]
I think we should document the official core package in each language where we build one.

**Comment by TamalSaha** [comment]
Thanks @garrettjonesgoogle

**Comment by TamalSaha** [comment]
The artifact id of these jar files seem to have changed between 0.1.5 and 0.1.9. I had to use the following jars:

```
compile 'com.google.api.grpc:googleapis-common-protos:0.0.3'
 compile 'com.google.api.grpc:proto-google-common-protos:0.1.9'
```
