### ISSUE TITLE
consider including a .go file to allow this package to be go-gettable.

### ISSUE THREAD

**Issue by tmc** [googleapis/googleapis#286]
Some open source projects may want to rely on the proto files here and having the project be 'go gettable' would be more convenient for users. I'm a maintainer of a project which currently duplicates a couple proto files and I would prefer to rely on this repository.

Having a .go file in this repository somewhere would simplify relying on these proto files as the go tool would clone this repository to local disks.

While I realize this is language specific and can legitimately be considered inappropriate it would assist in adoption of grpc.

**Comment by jmuk** [comment]
google.golang.org/genproto package contains the go files for those proto files.

**Comment by tmc** [comment]
@jmuk yes I'm aware. I'd like to not duplicate the .proto files in https://github.com/grpc-ecosystem/grpc-gateway

**Comment by jmuk** [comment]
This repository is for proto files and configuration files. We used to discuss about the go situation while ago, but we decided not to do that and that was why we made google.golang.org/genproto.

I'm still not sure what exactly is necessary here. If you just want the proto files, you could probably use git submodule?  (Sorry if I'm wrong, I'm not quite familiar with how go-get works with submodules).
