### ISSUE TITLE
Build broken due to "Http" is not defined

### ISSUE THREAD

**Issue by ankurcha** [googleapis/googleapis#30]
I tried building 23a607e43aa038fff25799b0034d81d807b5d429 and got the following error:

``` bash
google/api/service.proto:120:3: "Http" is not defined.
google/api/service.proto: warning: Import google/api/label.proto but not used.
google/api/service.proto: warning: Import google/protobuf/any.proto but not used.
google/api/service.proto: warning: Import google/api/http.proto but not used.
make: *** [google/api/service.pb.cc] Error 1
```

This was on a MacOS X El Capitan, protobuf compiled from source `17b6fc31eb8a9b65501cd7c53235a88efdc94394` and grpc compiled from source `26dd2b8d6b298b7225f317b66a05646aaefb6a48`. 

Am I missing something from the build?

**Comment by wora** [comment]
Fixed.

**Comment by bjwatson** [comment]
@wora What fixed this? Can this issue be closed?

**Comment by garrettjonesgoogle** [comment]
Closing out stale issue.
