### ISSUE TITLE
Objective C plugin fails

### ISSUE THREAD

**Issue by laurent-code8** [googleapis/googleapis#360]
> make LANGUAGE=objective_c all
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --objective_c_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_objective_c_plugin google/api/annotations.proto
protoc-gen-objective_c: program not found or is not executable
--objective_c_out: protoc-gen-objective_c: Plugin failed with status code 1.
make: *** [google/api/annotations.pb.cc] Error 1

How do can I provide more info or debug this?

**Comment by lukesneeringer** [comment]
Hi @laurent-code8,
I think you probably have the wrong repo; we are not the maintainers of protoc. Please file an issue [here](https://github.com/google/protobuf/issues).
