### ISSUE TITLE
Libraries not usable in Go

### ISSUE THREAD

**Issue by anantn** [googleapis/googleapis#39]
Running

```bash
LANGUAGE=go make all
```

with all the appropriate tools installed generates Go files in `$GOPATH/src/github.com/googleapis/googleapis/gens/google/...`.

These generated Go files contain imports of the form:

```go
import _ "google/api"
```

These import styles are not usable in a standard `$GOPATH` setup.

Is it intended for these APIs to be supported in Go?

**Comment by anantn** [comment]
Further:

```bash
$ ln -s $GOPATH/src/github.com/googleapis/googleapis/gens/google $GOPATH/src/google
```

which allows the imports to work, fails at compile time:

```bash
import cycle not allowed
package main
	imports google/cloud/speech/v1
	imports google/api
	imports google/api
```

**Comment by saicheems** [comment]
I'll be handling this issue, and I intend to fix most of the go related build this week for the api-compiler use cases.

I'm not immediately sure what's causing the import cycles, but they can occur if protos of the same package aren't compiled together - I didn't check if the makefile is doing that.

Manually, if you are compiling the pubsub protos:
```
protoc --go_out=plugins=grpc:. google/pubsub/v1/pubsub.proto
protoc --go_out=plugins=gprc:. google/protobuf/empty.proto google.protobuf/timestamp.proto
```

If you want a particular go package path for imports, include the `go_package` option in each of the compiled protos.
So:
```
// pubsub.proto
...
option go_package = "github.com/myorg/myrepo/pubsub/v1";

// timestamp.proto
option go_package = "github.com/myorg/myrepo/protobuf";

etc.
```

**Comment by anantn** [comment]
Sounds great, thanks for the response. I guess the two main asks are:

* Not generate imports of the form `google/...`
* Not generate cycles by default when using the `Makefile`.

Happy to test and give feedback as you land fixes!

**Comment by assumednormal** [comment]
I can't even get to the point of trying to use these libraries in go. Might this be related?

`$ make all LANGUAGE=go
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/annotations.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/auth.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/backend.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/billing.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/api/billing.proto" imports "google/api/metric.proto" which is not used.
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/consumer.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/context.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/control.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/documentation.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/http.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/label.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/log.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/logging.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/metric.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/monitored_resource.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/monitoring.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/service.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/api/service.proto" imports "google/protobuf/any.proto" which is not used.
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/api/service.proto" imports "google/api/label.proto" which is not used.
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/system_parameter.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/api/usage.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/bigtable/admin/table/v1/bigtable_table_data.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/bigtable/admin/table/v1/bigtable_table_service.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/bigtable/admin/table/v1/bigtable_table_service_messages.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/bigtable/v1/bigtable_data.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/bigtable/v1/bigtable_service.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/bigtable/v1/bigtable_service_messages.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/cloud/speech/v1/cloud_speech.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/container/v1/cluster_service.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/datastore/v1beta3/datastore.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/datastore/v1beta3/entity.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/datastore/v1beta3/query.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/datastore/v1beta3/query.proto" imports "google/type/latlng.proto" which is not used.
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/devtools/clouddebugger/v2/controller.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/devtools/clouddebugger/v2/controller.proto" imports "google/protobuf/empty.proto" which is not used.
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/devtools/clouddebugger/v2/data.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/devtools/clouddebugger/v2/debugger.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/devtools/cloudtrace/v1/trace.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/devtools/source/v1/source_context.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/example/library/v1/library.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/iam/v1/iam_policy.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/iam/v1/policy.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/logging/type/http_request.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/logging/type/log_severity.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/logging/v2/log_entry.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/logging/v2/logging.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/logging/v2/logging.proto" imports "google/protobuf/timestamp.proto" which is not used.
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/logging/v2/logging.proto" imports "google/protobuf/duration.proto" which is not used.
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/logging/v2/logging.proto" imports "google/rpc/status.proto" which is not used.
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/logging/v2/logging_config.proto
[libprotobuf WARNING google/protobuf/descriptor.cc:6220] Warning: Unused import: "google/logging/v2/logging_config.proto" imports "google/protobuf/timestamp.proto" which is not used.
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/logging/v2/logging_metrics.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/longrunning/operations.proto
mkdir -p ./gens
protoc --proto_path=.:/usr/local/include --go_out=plugins=grpc:./gens google/monitoring/v3/agent.proto
google/api/distribution.proto: File not found.
google/monitoring/v3/common.proto: Import "google/api/distribution.proto" was not found or had errors.
google/monitoring/v3/common.proto:47:5: "google.api.Distribution" is not defined.
google/monitoring/v3/agent.proto: Import "google/monitoring/v3/common.proto" was not found or had errors.
google/monitoring/v3/agent.proto:60:3: "TypedValue" is not defined.
google/monitoring/v3/agent.proto: "TypedValue" is not defined.
make: *** [google/monitoring/v3/agent.pb.go] Error 1`

**Comment by tmc** [comment]
@pongad I gather you're on this issue now?

**Comment by saicheems** [comment]
Hey guys, please take a look at this new repo we've put together for compiled Go protos (`googleapis` and `protobuf`):

https://github.com/google/go-genproto

Hopefully it should resolve the import style issues. Keep in mind it's experimental, and subject to change, but it's what we'll be using in Google Go clients going forward.

@pongad:
Resolving this issue should be a matter of adding `go_package` fields to each proto that point to the new `go-genproto` locations.

**Comment by pongad** [comment]
I reached out to @saicheems and confirmed that the action item at the end of last comment shouldn't be necessary. @anantn , does https://github.com/google/go-genproto have what you need?

**Comment by anantn** [comment]
Thanks @saicheems and @pongad -- the libraries at https://github.com/google/go-genproto are now importable and usable in Go!
