### ISSUE TITLE
How to working using C-core API

### ISSUE THREAD

**Issue by yookyoung89** [googleapis/googleapis#42]
I want to connect to google cloud speech API using C language. 
So, I need confirm about working steps. 
1. library and API
- APIs in grpc/include/grpc
- Libraries in grpc/libs/opt
(libboringssl.a, libgpr.a, libgrpc.a, libgrpc_plugin_support.a, libgrpc_unsecure.a, libz.a, 
libprotobuf.a, libprotoc.a)

Create client (1) grpc_init() 
(2) grpc_secure_channel_create() 
(3) grpc_completion_queue_create() 
(4) grpc_channel_create_call() 
(5) grpc_call_start_batch() : add options 
(6) grpc_completion_queue_next()
 (7) grpc_call_destroy() (8)grpc_shutdown()
Confirm please.

**Comment by tbetbetbe** [comment]
I think you probably want to raise this issue on the [grpc issue tracker](https://github.com/grpc/grpc/issues), not here.
