### ISSUE TITLE
Missing Vision Protobuf Files

### ISSUE THREAD

**Issue by blowmage** [googleapis/googleapis#52]
The vision protobuf references these file paths, but they are not provided by googleapis yet:

* `google/cloud/vision/v1/geometry.proto`
* `google/cloud/vision/v1/image_context_search_extension.proto`
* `google/cloud/vision/v1/query_annotation.proto`

**Comment by bjwatson** [comment]
@ethanbao Can you take a look?

**Comment by jba** [comment]
We're working on this. There are some issues with the internal publishing tool. Nothing huge, should be resolved soon.

**Comment by bjwatson** [comment]
Cool. Thanks @jba!

**Comment by jba** [comment]
They should be there now.

**Comment by blowmage** [comment]
Fantastic! Thanks all!
