### ISSUE TITLE
google/appengine: several issues with import

### ISSUE THREAD

**Issue by adamtanner** [googleapis/googleapis#74]
Hey team,

I noticed that the App Engine Admin API protos got imported a couple days back in cc198a87. I tried to run a regen for go-genproto to pull them in, but it failed when trying to import a couple missing protos in appengine.proto.

First, is the `app_yaml.proto` which I think was suppose to be included, but was missed.
Second, is the `firewall.proto` which I think should have its import removed.

cc: @ethanbao @pongad

**Comment by pgrosu** [comment]
Folks, how about just adding a continuous integration system like [Jenkins](https://jenkins.io/) that is working very well for the Protobuf and gRPC repositories.  Then each PR needs to pass the basic tests before being merged.

**Comment by bjwatson** [comment]
We do have CI-Travis setup on many of our repos, but apparently not this one. I'm interested in possibly using Jenkins, which I used previously at another job. I'd like to discuss how this has been done for Protobuf and gRPC.

**Comment by pgrosu** [comment]
So Jenkins would be good if reports are needed, but might require some tweaking.  It will help with separating out the builds (i.e. protobuf, gRPC, etc).  So to simplify life, maybe we would start with Travis and just have a script that builds ProtoBuf and gRPC, and then runs the Makefile to ensure there are no failures or missing dependencies.

What do you think?

**Comment by ethanbao** [comment]
That makes sense. We are now working on the appengine protos and the fix should be checked in very soon. At the same time, we will fix the currently-broken Makefile (https://github.com/googleapis/googleapis/blob/master/Makefile)

**Comment by adamtanner** [comment]
Awesome, thanks everyone. :+1:

**Comment by okdave** [comment]
+1 to adding CI testing to this repo. There are two other APIs which have been recently added that also are missing their deps.

**Comment by ethanbao** [comment]
Appengine protos have been added/updated.

**Comment by adamtanner** [comment]
Where? I don't see them in master and there's no recent PR for them.

**Comment by adamtanner** [comment]
Fixed in f2df330.
