### ISSUE TITLE
logging/type: add RequestLog proto

### ISSUE THREAD

**Issue by adamtanner** [googleapis/googleapis#90]
For parsing logs from App Engine Standard they are (I think) only available as a serialized RequestLog proto in the protoPayload field of a LogEntry. I can point you to the necessary proto files internally if needed. Thanks!

\cc @ethanbao

**Comment by bjwatson** [comment]
Done: https://github.com/googleapis/googleapis/blob/master/google/appengine/logging/v1/request_log.proto
